---
- name: Manage 3 VMs
  hosts: localhost
  gather_facts: no
  vars:
    machines:
      - vm-kafka-01
      - vm-kafka-02
      - vm-kafka-03
  tasks:
    - name: Create VMs
      ansible.builtin.include_role:
        name: cloud-init-vm
        apply:
          tags: always
      vars:
        vm_name: "{{ item }}"
      loop: "{{ machines }}"
      tags: create
    - name: Destroy VMs
      ansible.builtin.include_role:
        name: delete-vm
        apply:
          tags: always
      vars:
        vm_name: "{{ item }}"
      loop: "{{ machines }}"
      tags: destroy
    # Shutdown VMs
    - name: Shutdown VMs
      ansible.builtin.command: "virsh -c qemu:///system shutdown --domain {{ item }}"
      ignore_errors: yes
      loop: "{{ machines }}"
      tags: shutdown
    # Start VMs
    - name: Start VMs
      ansible.builtin.command: "virsh -c qemu:///system start --domain {{ item }}"
      ignore_errors: yes
      loop: "{{ machines }}"
      tags: start
