---
- name: systemd_reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: jellyfin_restart
  ansible.builtin.systemd_service:
    state: restarted
    name: jellyfin
    scope: user
