---
- name: Setup pod for Immich
  ansible.builtin.import_tasks: immich-pod.yml

- name: Setup PostgreSQL for Immich
  ansible.builtin.import_tasks: postgresql.yml

- name: Setup Redis for Immich
  ansible.builtin.import_tasks: redis.yml

- name: Setup Immich server
  ansible.builtin.import_tasks: immich-server.yml

- name: Setup Immich ML
  ansible.builtin.import_tasks: immich-ml.yml
