---
- name: Create Immich pod
  containers.podman.podman_pod:
    name: immich
    state: quadlet
    label:
      app: immich
    ports:
      - "3001:3001"
  notify:
    - reload systemd

- name: Create PostgreSQL data volume
  containers.podman.podman_volume:
    name: immich-postgresql-data
    label:
      app: immich
    state: quadlet
  notify:
    - reload systemd

- name: Create secret with PostgreSQL username
  containers.podman.podman_secret:
    name: immich-postgresql-user
    labels:
      app: immich
    data: "immich"
  notify:
    - reload systemd

- name: Create secret with random PostgreSQL password
  containers.podman.podman_secret:
    name: immich-postgresql-password
    labels:
      app: immich
    data: "{{ lookup('ansible.builtin.password', '/dev/null', lenght=20) }}"
    skip_existing: true
  notify:
    - reload systemd

- name: Create PostgreSQL container for Immich
  containers.podman.podman_container:
    name: immich-postgresql
    pod: immich.pod
    label:
      app: immich
    image: "{{ immich_postgresql_image }}:{{ immich_postgresql_tag }}"
    state: quadlet
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "immich-postgresql-data.volume:/var/lib/postgresql/data:z"
    secrets:
      - "immich-postgresql-user,type=env,target=POSTGRES_USER"
      - "immich-postgresql-password,type=env,target=POSTGRES_PASSWORD"
    env:
      POSTGRES_DB: '{{ immich_postgresql_dbname }}'
      POSTGRES_INITDB_ARGS: '--data-checksums'
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Install]
        RequiredBy=immich-server.service
  notify:
    - reload systemd

- name: Create Redis container
  containers.podman.podman_container:
    name: immich-redis
    label:
      app: immich
    pod: immich.pod
    image: "{{ immich_redis_image }}:{{ immich_redis_tag }}"
    state: quadlet
    rm: true
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Install]
        RequiredBy=immich-server.service
  notify:
    - reload systemd

- name: Create Immich data volume
  containers.podman.podman_volume:
    name: immich-data
    label:
      app: immich
    state: quadlet
  notify:
    - reload systemd

- name: Create Immich server container
  containers.podman.podman_container:
    name: immich-server
    pod: immich.pod
    label:
      app: immich
    state: quadlet
    image: "{{ immich_server_image }}:{{ immich_server_tag }}"
    volume:
      - "/etc/localtime:/etc/localtime:ro"
      - "immich-data.volume:/usr/src/app/upload:z"
    env:
      DB_HOSTNAME: localhost
      DB_DATABASE_NAME: '{{ immich_postgresql_dbname }}'
      REDIS_HOSTNAME: localhost
    secrets:
      - "immich-postgresql-user,type=env,target=DB_USERNAME"
      - "immich-postgresql-password,type=env,target=DB_PASSWORD"
  notify:
    - reload systemd

- name: Create volume for Immich model cache
  containers.podman.podman_volume:
    name: immich-model-cache
    label:
      app: immich
    state: quadlet
  notify:
    - reload systemd

- name: Create Immich ML container
  containers.podman.podman_container:
    name: immich-ml
    pod: immich.pod
    label:
      app: immich
    state: quadlet
    image: "{{ immich_ml_image }}:{{ immich_ml_tag }}"
    volume:
      - "immich-model-cache.volume:/cache"
    quadlet_options:
      - "AutoUpdate=registry"
      - |
        [Install]
        RequiredBy=immich-server.service
  notify:
    - reload systemd
