---
# Setup the most basic things required to run other playbooks
- name: Install dnf-automatic
  hosts: all
  become: yes
  tasks:
    - dnf:
        name: dnf-automatic
        state: latest

- name: Only auto-install security updates
  hosts: all
  become: yes
  tasks:
    - lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^upgrade_type'
        line: 'upgrade_type=security'
        state: present
        mode: 0644
        owner: root
        group: root

- name: Enable dnf-automatic-install timer
  hosts: all
  become: yes
  tasks:
    - systemd:
        name: dnf-automatic-install.timer
        enabled: yes
        state: started
