---
# Setup the most basic things required to run other playbooks
- name: Ansible requries libselinux-python
  hosts: all
  become: yes
  tasks:
    - dnf:
        name: python3-libselinux
        state: latest

- name: Setup sudoers
  hosts: all
  become: yes
  tasks:
    - lineinfile:
        path: /etc/sudoers.d/10-martin
        line: 'martin ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        owner: root
        group: root
        create: yes
        validate: 'visudo -cf %s'

- name: Install dnf-automatic
  hosts: all
  become: yes
  tasks:
    - dnf:
        name: dnf-automatic
        state: latest

- name: Only auto-install security updates
  hosts: all
  become: yes
  tasks:
    - lineinfile:
        path: /etc/dnf/automatic.conf
        regexp: '^upgrade_type'
        line: 'upgrade_type=security'
        state: present
        mode: 0644
        owner: root
        group: root

- name: Enable dnf-automatic-install timer
  hosts: all
  become: yes
  tasks:
    - systemd:
        name: dnf-automatic-install.timer
        enabled: yes
        state: started
