---
# Setup the most basic things required to run other playbooks
- name: Setup sudoers
  hosts: all
  become: yes
  tasks:
    - lineinfile:
        path: /etc/sudoers.d/10-martin
        line: 'martin ALL=(ALL) NOPASSWD: ALL'
        state: present
        mode: 0440
        owner: root
        group: root
        create: yes
        validate: 'visudo -cf %s'
