---
- name: Cleanup VM
  hosts: localhost
  tasks:
    - name: Load common variables
      include_vars: common-vars.yaml
    - name: Shutdown VM
      command: "virsh -c qemu:///system shutdown {{ vm_name }}"
      ignore_errors: yes
    - name: Remove VM
      command: "virsh -c qemu:///system undefine {{ vm_name }}"
      ignore_errors: yes
    - name:  Remove disk image
      file:
        path: "{{ dest_path }}"
        state: absent
    - name:  Remove meta-data.yaml
      file:
        path: "{{ meta_data }}"
        state: absent
    - name:  Remove user-data.yaml
      file:
        path: "{{ user_data }}"
        state: absent
