---
- name: Create directory for user units
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/.config/containers/systemd'
    state: directory
    mode: '0755'

- name: Write systemd unit for config volume
  ansible.builtin.template:
    src: 'jellyfin-config.volume.j2'
    dest: '{{ ansible_user_dir }}/.config/containers/systemd/jellyfin-config.volume'
    mode: '0644'
  notify:
    - jellyfin_restart

- name: Write systemd unit for cache volume
  ansible.builtin.template:
    src: 'jellyfin-cache.volume.j2'
    dest: '{{ ansible_user_dir }}/.config/containers/systemd/jellyfin-cache.volume'
    mode: '0644'
  notify:
    - jellyfin_restart

- name: Write systemd unit for container
  ansible.builtin.template:
    src: 'jellyfin.container.j2'
    dest: '{{ ansible_user_dir }}/.config/containers/systemd/jellyfin.container'
    mode: '0644'
  notify:
    - jellyfin_restart

- name: Configure firewall for Jellyfin
  become: true
  firewalld:
    state: enabled
    permanent: true
    zone: public
    immediate: true
    port: 8096/tcp
