---
- name: Install dnf-automatic
  become: true
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Only auto-install security updates
  become: true
  ansible.builtin.lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: '^upgrade_type'
    line: 'upgrade_type=security'
    state: present
    mode: '0644'
    owner: root
    group: root

- name: Enable dnf-automatic-install timer
  become: true
  ansible.builtin.systemd_service:
    name: dnf-automatic-install.timer
    enabled: true
    state: started
